@host = localhost:44371

### Encrypt
POST https://{{host}}/APIGateway/Encrypt HTTP/1.1
Content-Type: application/json

"blah"

### Decrypt
POST https://{{host}}/APIGateway/Decrypt HTTP/1.1
Content-Type: application/json

"blah"

### Health Check
GET https://{{host}}/APIGateway/HealthCheck HTTP/1.1
